name: Release & Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Trigger on tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Specify release type: regular, alpha, beta, or rc'
        required: true
        default: 'regular'
        type: choice
        options:
          - regular
          - alpha
          - beta
          - rc

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}

    steps:
      - name: Validate branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: This workflow can only be run on the main branch."
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm ci

      - name: Set Git user
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Run release-it
        run: |
          if [ "$RELEASE_TYPE" == "regular" ]; then
            npx release-it
          else
            npx release-it --preRelease="$RELEASE_TYPE"
          fi
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

      - name: Print success message
        if: success()
        run: echo "Release completed successfully!"

      - name: Handle failure
        if: failure()
        run: echo "Release process failed."

  publish:
    needs: release  # Ensure this job runs after the 'release' job completes
    permissions:
      id-token: write  # Required for authentication using OIDC
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest  # Specify the environment
    steps:
      - name: Publish to pub.dev
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

      - name: Print tag publish success
        run: echo "Tag published successfully!"

  print-tag-not-published:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Notify tag not published
        run: echo "Tag not published, no release occurred."
